### ISSUE TITLE
cmake file provided doesn't allows to satisfy requirement of lxqt-menu-data

### ISSUE THREAD

**Issue by papoteur-mga** [lxqt/lxqt-menu-data#17] opened 2023-11-05 17:00 UTC
##### Expected Behavior
Other packages find lxqt-menu-data
##### Current Behavior
> Could not find a configuration file for package "lxqt-menu-data" that is
> compatible with requested version "1.4.0".
>
> The following configuration files were considered but not accepted:
>
>    /usr/share/cmake/lxqt-menu-data/lxqt-menu-data-config.cmake, version: 1.4.0 (64bit)

##### Possible Solution
In the built package, there is a section:

> check that the installed version has the same 32/64bit-ness as the one which is currently searching:

I don't know where it comes from, but this is probably not wanted as we have this package as noarch (only data)

##### Steps to Reproduce (for bugs)
1. Build lxqt-menu-data and install
2. try to build libfm-qt: it fails

##### Context
Trying to package LXQt 1.4.0 for Mageia
##### System Information                               --->
* Distribution & Version: Mageia cauldron
* Qt Version: 5.15.7
* liblxqt Version: 1.4.0
* lxqt-build-tools Version: 0.13.0
* Package version: 1.4.0

**Comment by stefonarch** [comment] 2023-11-05 17:53
Did you follow the build order?
https://github.com/lxqt/lxqt/wiki/Building-from-source#generalbuild-order

Cannot reproduce here.

**Comment by papoteur-mga** [comment] 2023-11-05 18:30
No, the order is OK.
I forgotten to notice that this failing build is on 32 bits arch.

**Comment by papoteur-mga** [comment] 2023-11-05 20:23
The file `/usr/share/cmake/lxqt-menu-data/lxqt-menu-data-config-version.cmake` contains
```
# This is a basic version file for the Config-mode of find_package().
# It is used by write_basic_package_version_file() as input file for configure_file()
# to create a version-file which can be installed along a config.cmake file.
#
# The created file sets PACKAGE_VERSION_EXACT if the current version string and
# the requested version string are exactly the same and it sets
# PACKAGE_VERSION_COMPATIBLE if the current version is >= requested version.
# The variable CVF_VERSION must be set before calling configure_file().

set(PACKAGE_VERSION "1.4.0")

if (PACKAGE_FIND_VERSION_RANGE)
  # Package version must be in the requested version range
  if ((PACKAGE_FIND_VERSION_RANGE_MIN STREQUAL "INCLUDE" AND PACKAGE_VERSION VERSION_LESS PACKAGE_FIND_VERSION_MIN)
      OR ((PACKAGE_FIND_VERSION_RANGE_MAX STREQUAL "INCLUDE" AND PACKAGE_VERSION VERSION_GREATER PACKAGE_FIND_VERSION_MAX)
        OR (PACKAGE_FIND_VERSION_RANGE_MAX STREQUAL "EXCLUDE" AND PACKAGE_VERSION VERSION_GREATER_EQUAL PACKAGE_FIND_VERSION_MAX)))
    set(PACKAGE_VERSION_COMPATIBLE FALSE)
  else()
    set(PACKAGE_VERSION_COMPATIBLE TRUE)
  endif()
else()
  if(PACKAGE_VERSION VERSION_LESS PACKAGE_FIND_VERSION)
    set(PACKAGE_VERSION_COMPATIBLE FALSE)
  else()
    set(PACKAGE_VERSION_COMPATIBLE TRUE)
    if(PACKAGE_FIND_VERSION STREQUAL PACKAGE_VERSION)
      set(PACKAGE_VERSION_EXACT TRUE)
    endif()
  endif()
endif()


# if the installed or the using project don't have CMAKE_SIZEOF_VOID_P set, ignore it:
if("${CMAKE_SIZEOF_VOID_P}" STREQUAL "" OR "8" STREQUAL "")
  return()
endif()

# check that the installed version has the same 32/64bit-ness as the one which is currently searching:
if(NOT CMAKE_SIZEOF_VOID_P STREQUAL "8")
  math(EXPR installedBits "8 * 8")
  set(PACKAGE_VERSION "${PACKAGE_VERSION} (${installedBits}bit)")
  set(PACKAGE_VERSION_UNSUITABLE TRUE)
endif()
```
The expression `math(EXPR installedBits "8 * 8")` is false in the context of a build for 32 bits.

**Comment by luis-pereira** [comment] 2023-11-06 09:53
@papoteur-mga Are you running on a 32bit system ?
`if("${CMAKE_SIZEOF_VOID_P}" STREQUAL "" OR "8" STREQUAL "")`  was generated in a 64 bits system.

`ARCH_INDEPENDENT` requires CMake >= 3.14. LXQt current CMake requirement is 3.0.1.
`ARCH_INDEPENDENT`  will be introduced after we update CMake requirements. This will happen in the Qt6 version.

**Comment by papoteur-mga** [comment] 2023-11-06 12:14
> @papoteur-mga Are you running on a 32bit system ? `if("${CMAKE_SIZEOF_VOID_P}" STREQUAL "" OR "8" STREQUAL "")` was generated in a 64 bits system.

No, this is a run from our build system which does cross compilation for 64bits and 32 bits x86 through chroot (the same for arm v7 and v8 on another build node).
Our package lxqt-menu-data was tagged as noarch because it does not have binary files. But now, the cmake file is distinct according to arches, which is not of any added value.

**Comment by tsimonq2** [comment] 2023-11-06 12:38
We are also facing this issue in Lubuntu. Unless it's fixed here by a newer CMake *before* Qt 6 is merged in, we will probably be doing this (and test rebuilding the stack) ourselves. 

This is currently blocking the transition in Lubuntu. You mentioned you cannot reproduce it, so something must be different.

**Comment by tsimonq2** [comment] 2023-11-06 14:15
I do get this warning on every package build: `Compatibility with CMake < 3.5 will be removed from a future version of CMake.` It's not just a "nice to have" :)

**Comment by ArrayBolt3** [comment] 2023-11-06 15:05
I think the problem here is that lxqt-menu-data is being built on a 64-bit arch, but then libfm-qt is being built on a 32-bit arch. This happens commonly in distro build infrastructure, as arch-independent packages are oftentimes built on amd64 builders, whereas arch-dependent packages are built on whatever architecture they are for. lxqt-menu-data is arch-independent (or so it seems), so distro packagers mark it as such, and so it gets built on an amd64 builder. Then libfm-qt is built on an i386 or armhf machine (which is 32-bit), and that's when troubles occur. (In the context of Lubuntu, this is causing a libfm-qt build failure for the armhf architecture only, whereas all our 64-bit arches build successfully.)

The 64-bit build of lxqt-menu-data ought to work on a 32-bit arch since there isn't anything arch-dependent about lxqt-menu-data in theory. In practice, however, the `lxqt-menu-data-config-version.cmake` file contains an arch bitness check that makes lxqt-menu-data arch-dependent when it shouldn't be. Thus, if you build lxqt-menu-data on an amd64 builder and then try to use that package with an armhf build, the build fails.

Adding `ARCH_INDEPENDENT` to the `write_basic_package_version_file` call like @papoteur-mga suggested above should tell CMake that this is an arch-independent package and make it so that this doesn't happen any more. I haven't tested this yet, though I intend to.

**Comment by ArrayBolt3** [comment] 2023-11-06 19:48
I can verify that the fix detailed above works to fix this bug. After patching lxqt-menu-data's CMakeLists.txt file to add `ARCH_INDEPENDENT` to the `write_basic_package_version_file` call and rebuilding it, libfm-qt now builds on both 32-bit and 64-bit arches without issues.

**Comment by yan12125** [comment] 2023-11-07 06:08
I'm fine with bumping CMake requirement to 3.14. Qt 5.15 was out in 2020 [1] and CMake 3.14 was out in 2019 [2], so systems running LXQt should already come with recent CMake.

[1] https://www.qt.io/blog/qt-5.15-released
[2] https://www.kitware.com/cmake-3-14-0-available-for-download/

**Comment by luis-pereira** [comment] 2023-11-07 16:53
@papoteur-mga Fix at https://github.com/lxqt/lxqt-menu-data/pull/18.

**Closed** 2023-11-08 21:15 UTC
